[package]
name = "aoc_2019_03"
version = "0.1.0"
authors = ["kzc16"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
