[package]
name = "aoc_2019_07"
version = "0.1.0"
authors = ["Zichun Koh <zichun@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
